// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// @brief Available CPU features.
abstract class CpuFeatures {
  static const int CPU_MMX = 1;
  static const int CPU_SSE = 2;
  static const int CPU_SSE2 = 3;
  static const int CPU_SSE3 = 4;
  static const int CPU_SSSE3 = 5;
  static const int CPU_SSE4_1 = 6;
  static const int CPU_SSE4_2 = 7;
  static const int CPU_POPCNT = 8;
  static const int CPU_FP16 = 9;
  static const int CPU_AVX = 10;
  static const int CPU_AVX2 = 11;
  static const int CPU_FMA3 = 12;
  static const int CPU_AVX_512F = 13;
  static const int CPU_AVX_512BW = 14;
  static const int CPU_AVX_512CD = 15;
  static const int CPU_AVX_512DQ = 16;
  static const int CPU_AVX_512ER = 17;
  static const int CPU_AVX_512IFMA512 = 18;
  static const int CPU_AVX_512IFMA = 18;
  static const int CPU_AVX_512PF = 19;
  static const int CPU_AVX_512VBMI = 20;
  static const int CPU_AVX_512VL = 21;
  static const int CPU_AVX_512VBMI2 = 22;
  static const int CPU_AVX_512VNNI = 23;
  static const int CPU_AVX_512BITALG = 24;
  static const int CPU_AVX_512VPOPCNTDQ = 25;
  static const int CPU_AVX_5124VNNIW = 26;
  static const int CPU_AVX_5124FMAPS = 27;
  static const int CPU_NEON = 100;
  static const int CPU_MSA = 150;
  static const int CPU_RISCVV = 170;
  static const int CPU_VSX = 200;
  static const int CPU_VSX3 = 201;
  static const int CPU_RVV = 210;

  /// !< Skylake-X with AVX-512F/CD/BW/DQ/VL
  static const int CPU_AVX512_SKX = 256;

  /// !< Common instructions AVX-512F/CD for all CPUs that support AVX-512
  static const int CPU_AVX512_COMMON = 257;

  /// !< Knights Landing with AVX-512F/CD/ER/PF
  static const int CPU_AVX512_KNL = 258;

  /// !< Knights Mill with AVX-512F/CD/ER/PF/4FMAPS/4VNNIW/VPOPCNTDQ
  static const int CPU_AVX512_KNM = 259;

  /// !< Cannon Lake with AVX-512F/CD/BW/DQ/VL/IFMA/VBMI
  static const int CPU_AVX512_CNL = 260;

  /// !< Cascade Lake with AVX-512F/CD/BW/DQ/VL/VNNI
  static const int CPU_AVX512_CLX = 261;

  /// !< Ice Lake with AVX-512F/CD/BW/DQ/VL/IFMA/VBMI/VNNI/VBMI2/BITALG/VPOPCNTDQ
  static const int CPU_AVX512_ICL = 262;
  static const int CPU_MAX_FEATURE = 512;
}

class Cv16suf extends ffi.Union {
  @ffi.Short()
  external int i;

  @ushort()
  external int u;
}

typedef ushort = ffi.UnsignedShort;

class Cv32suf extends ffi.Union {
  @ffi.Int()
  external int i;

  @ffi.UnsignedInt()
  external int u;

  @ffi.Float()
  external double f;
}

class Cv64suf extends ffi.Union {
  @int64()
  external int i;

  @uint64()
  external int u;

  @ffi.Double()
  external double f;
}

typedef int64 = ffi.LongLong;
typedef uint64 = ffi.UnsignedLongLong;

const int CV_VERSION_MAJOR = 4;

const int CV_VERSION_MINOR = 6;

const int CV_VERSION_REVISION = 0;

const String CV_VERSION_STATUS = '';

const String CV_VERSION = '4.6.0';

const int CV_MAJOR_VERSION = 4;

const int CV_MINOR_VERSION = 6;

const int CV_SUBMINOR_VERSION = 0;

const int CV_HAL_ERROR_OK = 0;

const int CV_HAL_ERROR_NOT_IMPLEMENTED = 1;

const int CV_HAL_ERROR_UNKNOWN = -1;

const int CV_CN_MAX = 512;

const int CV_CN_SHIFT = 3;

const int CV_DEPTH_MAX = 8;

const int CV_8U = 0;

const int CV_8S = 1;

const int CV_16U = 2;

const int CV_16S = 3;

const int CV_32S = 4;

const int CV_32F = 5;

const int CV_64F = 6;

const int CV_16F = 7;

const int CV_MAT_DEPTH_MASK = 7;

const int CV_8UC1 = 0;

const int CV_8UC2 = 8;

const int CV_8UC3 = 16;

const int CV_8UC4 = 24;

const int CV_8SC1 = 1;

const int CV_8SC2 = 9;

const int CV_8SC3 = 17;

const int CV_8SC4 = 25;

const int CV_16UC1 = 2;

const int CV_16UC2 = 10;

const int CV_16UC3 = 18;

const int CV_16UC4 = 26;

const int CV_16SC1 = 3;

const int CV_16SC2 = 11;

const int CV_16SC3 = 19;

const int CV_16SC4 = 27;

const int CV_32SC1 = 4;

const int CV_32SC2 = 12;

const int CV_32SC3 = 20;

const int CV_32SC4 = 28;

const int CV_32FC1 = 5;

const int CV_32FC2 = 13;

const int CV_32FC3 = 21;

const int CV_32FC4 = 29;

const int CV_64FC1 = 6;

const int CV_64FC2 = 14;

const int CV_64FC3 = 22;

const int CV_64FC4 = 30;

const int CV_16FC1 = 7;

const int CV_16FC2 = 15;

const int CV_16FC3 = 23;

const int CV_16FC4 = 31;

const int CV_HAL_CMP_EQ = 0;

const int CV_HAL_CMP_GT = 1;

const int CV_HAL_CMP_GE = 2;

const int CV_HAL_CMP_LT = 3;

const int CV_HAL_CMP_LE = 4;

const int CV_HAL_CMP_NE = 5;

const int CV_HAL_BORDER_CONSTANT = 0;

const int CV_HAL_BORDER_REPLICATE = 1;

const int CV_HAL_BORDER_REFLECT = 2;

const int CV_HAL_BORDER_WRAP = 3;

const int CV_HAL_BORDER_REFLECT_101 = 4;

const int CV_HAL_BORDER_TRANSPARENT = 5;

const int CV_HAL_BORDER_ISOLATED = 16;

const int CV_HAL_DFT_INVERSE = 1;

const int CV_HAL_DFT_SCALE = 2;

const int CV_HAL_DFT_ROWS = 4;

const int CV_HAL_DFT_COMPLEX_OUTPUT = 16;

const int CV_HAL_DFT_REAL_OUTPUT = 32;

const int CV_HAL_DFT_TWO_STAGE = 64;

const int CV_HAL_DFT_STAGE_COLS = 128;

const int CV_HAL_DFT_IS_CONTINUOUS = 512;

const int CV_HAL_DFT_IS_INPLACE = 1024;

const int CV_HAL_SVD_NO_UV = 1;

const int CV_HAL_SVD_SHORT_UV = 2;

const int CV_HAL_SVD_MODIFY_A = 4;

const int CV_HAL_SVD_FULL_UV = 8;

const int CV_HAL_GEMM_1_T = 1;

const int CV_HAL_GEMM_2_T = 2;

const int CV_HAL_GEMM_3_T = 4;

const int CV_ENABLE_UNROLLED = 1;

const int CV_CPU_NONE = 0;

const int CV_CPU_MMX = 1;

const int CV_CPU_SSE = 2;

const int CV_CPU_SSE2 = 3;

const int CV_CPU_SSE3 = 4;

const int CV_CPU_SSSE3 = 5;

const int CV_CPU_SSE4_1 = 6;

const int CV_CPU_SSE4_2 = 7;

const int CV_CPU_POPCNT = 8;

const int CV_CPU_FP16 = 9;

const int CV_CPU_AVX = 10;

const int CV_CPU_AVX2 = 11;

const int CV_CPU_FMA3 = 12;

const int CV_CPU_AVX_512F = 13;

const int CV_CPU_AVX_512BW = 14;

const int CV_CPU_AVX_512CD = 15;

const int CV_CPU_AVX_512DQ = 16;

const int CV_CPU_AVX_512ER = 17;

const int CV_CPU_AVX_512IFMA512 = 18;

const int CV_CPU_AVX_512IFMA = 18;

const int CV_CPU_AVX_512PF = 19;

const int CV_CPU_AVX_512VBMI = 20;

const int CV_CPU_AVX_512VL = 21;

const int CV_CPU_AVX_512VBMI2 = 22;

const int CV_CPU_AVX_512VNNI = 23;

const int CV_CPU_AVX_512BITALG = 24;

const int CV_CPU_AVX_512VPOPCNTDQ = 25;

const int CV_CPU_AVX_5124VNNIW = 26;

const int CV_CPU_AVX_5124FMAPS = 27;

const int CV_CPU_NEON = 100;

const int CV_CPU_MSA = 150;

const int CV_CPU_RISCVV = 170;

const int CV_CPU_VSX = 200;

const int CV_CPU_VSX3 = 201;

const int CV_CPU_RVV = 210;

const int CV_CPU_AVX512_SKX = 256;

const int CV_CPU_AVX512_COMMON = 257;

const int CV_CPU_AVX512_KNL = 258;

const int CV_CPU_AVX512_KNM = 259;

const int CV_CPU_AVX512_CNL = 260;

const int CV_CPU_AVX512_CLX = 261;

const int CV_CPU_AVX512_ICL = 262;

const int CV_HARDWARE_MAX_FEATURE = 512;

const int CV_MMX = 1;

const int CV_SSE = 1;

const int CV_SSE2 = 1;

const int CV_SSE3 = 0;

const int CV_SSSE3 = 0;

const int CV_SSE4_1 = 0;

const int CV_SSE4_2 = 0;

const int CV_POPCNT = 0;

const int CV_AVX = 0;

const int CV_FP16 = 0;

const int CV_AVX2 = 0;

const int CV_FMA3 = 0;

const int CV_AVX_512F = 0;

const int CV_AVX_512BW = 0;

const int CV_AVX_512CD = 0;

const int CV_AVX_512DQ = 0;

const int CV_AVX_512ER = 0;

const int CV_AVX_512IFMA = 0;

const int CV_AVX_512IFMA512 = 0;

const int CV_AVX_512PF = 0;

const int CV_AVX_512VBMI = 0;

const int CV_AVX_512VL = 0;

const int CV_AVX_5124FMAPS = 0;

const int CV_AVX_5124VNNIW = 0;

const int CV_AVX_512VPOPCNTDQ = 0;

const int CV_AVX_512VNNI = 0;

const int CV_AVX_512VBMI2 = 0;

const int CV_AVX_512BITALG = 0;

const int CV_AVX512_COMMON = 0;

const int CV_AVX512_KNL = 0;

const int CV_AVX512_KNM = 0;

const int CV_AVX512_SKX = 0;

const int CV_AVX512_CNL = 0;

const int CV_AVX512_CLX = 0;

const int CV_AVX512_ICL = 0;

const int CV_NEON = 0;

const int CV_RVV071 = 0;

const int CV_VSX = 0;

const int CV_VSX3 = 0;

const int CV_MSA = 0;

const int CV_WASM_SIMD = 0;

const int CV_RVV = 0;

const int CV_STRONG_ALIGNMENT = 0;

const double CV_PI = 3.141592653589793;

const double CV_2PI = 6.283185307179586;

const double CV_LOG2 = 0.6931471805599453;

const int CV_FP16_TYPE = 0;

const int OPENCV_ABI_COMPATIBILITY = 400;

const int CV_MAT_CN_MASK = 4088;

const int CV_MAT_TYPE_MASK = 4095;

const int CV_MAT_CONT_FLAG_SHIFT = 14;

const int CV_MAT_CONT_FLAG = 16384;

const int CV_SUBMAT_FLAG_SHIFT = 15;

const int CV_SUBMAT_FLAG = 32768;

const int CV_CXX11 = 1;

const int CV_CXX_MOVE_SEMANTICS = 1;

const int CV_CXX_STD_ARRAY = 1;

const String CV__CHECK_FILENAME = 'temp_for_macros.hpp';

const int OPENCV_USE_FASTMATH_BUILTINS = 1;
